zendesk/arturo

app/controllers/arturo/features_controller.rb
config/locales/en.yml
test/dummy_app/test/functional/features_controller_admin_test.rb

We added a validation and it caused the updating to error out but this exposed the fact that there was missing data in the interpolated error message.
@jamesarosen 
Without fix (failing test):
````
ArturoFeaturesControllerAdminTest#test_put_invalid_update:
I18n::MissingInterpolationArgument: missing interpolation argument :id in "Could not update feature #%{id}: %{errors}." ({:name=>"Feature Feature 41", :errors=>#<ActiveModel::Errors:0x007feb598fb780 @base=<Arturo::Feature Feature 41, deployed to -10%>, @messages={:deployment_percentage=>["must be greater than or equal to 0"]}>} given)
````

Pass in needed interpolation data

---

lib/arturo.rb

Some gems will declare the `Rails` module even without having a dependency on the rails gem.
I'm looking at you `rails-dom-testing`.
https://github.com/rails/rails-dom-testing/blob/master/lib/rails/dom/testing/version.rb
So you can end up with a `Rails` module without a `VERSION` constant.
Hi James!

check for definition of Rails::VERSION::MAJOR

---

lib/arturo/engine.rb

:octopus::computer:
/cc @grosser @bquorning 
Fails if you include the gem in a Rails 5 application in API mode.
* None

Verify if helper is defined for Rails 5 API mode

---

lib/arturo/feature.rb

allow threshold argument to `passes_threshold?` to enable re-use in subclasses

---

spec/models/feature_spec.rb

- Add a spec for rollout behavior for specific accounts
- See https://github.com/zendesk/zendesk_core_scala/pull/267
@zendesk/hadoken

Add rollout spec for parity with Scala implementation

---

lib/arturo/feature.rb

This does not fail in Rails 6.0 but will fail in Rails 6.1
There are dependent gems that fail specs due to `config.active_support.deprecations :raise` and rather than updating those gems to remove this configuration, we are updating `arturo` uniqueness validator to include the `case_sensitive` flag.
Will need to merge [112](https://github.com/zendesk/arturo/pull/112) first
JIRA: https://zendesk.atlassian.net/browse/WALR-2077
Issue: https://github.com/rails/rails/commit/9def05385f1cfa41924bb93daa187615e88c95b9
**Low**

update uniqueness validator

---

lib/arturo.rb

@bquorning internally we had be using the gem in a non rails app with ActiveRecord being the ORM. The changes in 2.5.2 broke this for us. I have changed the line which is of concern to us. Feel free to comment and contact me through other channels to discuss this.

Using the gem in a non-rails environment (but with AR)

---

lib/arturo/engine.rb

**Description:** 
Explicitly require rails engine to avoid errors that `::Rails::Engine` cannot be found.
We discovered this error while working on migrating the the MPQ service to use Sentry:
```sh
[mail_parsing_queue /app (mariozaizar/EM-7115)] ➔ bundle exec rake test
/bundle/ruby/2.6.0/gems/active_record_host_pool-1.0.3/lib/active_record_host_pool/connection_adapter_mixin.rb:95: warning: method redefined; discarding old establish_connection
/bundle/ruby/2.6.0/gems/activerecord-5.2.6.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:973: warning: previous definition of establish_connection was here
/bundle/ruby/2.6.0/gems/zendesk_database_support-1.44.3/lib/zendesk_database_support/account_master_reconnection.rb:52: warning: method redefined; discarding old active? …
```

[EM-7115] Explicitly require rails engine - part of MPQ sentry migration

---

.github/workflows/ci.yml
CHANGELOG.md
arturo.gemspec
gemfiles/rails4.2.gemfile
lib/arturo/controller_filters.rb
spec/controllers/controller_filters_spec.rb
spec/controllers/features_controller_admin_spec.rb
spec/controllers/features_controller_non_admin_spec.rb
spec/dummy_app/app/controllers/books_controller.rb
spec/dummy_app/config/application.rb

It also simplfies the CI. Configuring GitHub to have many required tests is hard to maintain.
In fact, the admin needs to duplicate what is defined in the actions.yml test matrix. It should be quite a bit easier this way, just having one CI job that depends on the success of the entire test matrix.

Drop Ruby 2.4, 2.5 and Rails 4.2

---

.github/workflows/ci.yml
app/controllers/arturo/features_controller.rb
arturo.gemspec
gemfiles/rails7.0.gemfile
spec/dummy_app/config/application.rb

Rails 7.0 is only compatible with Ruby 2.7+ so we don't test it with Ruby 2.6
`unloadable` was moved in Rails but I opted to just remove it from `app/controllers/arturo/features_controller.rb`. That will affect the `development` environment but I don't really think it's much of an impact.

Add support for Rails 7.0

---

CHANGELOG.md
lib/arturo/version.rb

- Adds support for Ruby 3.0 & 3.1 #125
- Add support for Rails 7.0  #124
- Drops support for Ruby 2.4, 2.5, and 4.2 #123

Release v2.6.0

---

.github/workflows/ci.yml
CHANGELOG.md
arturo.gemspec
gemfiles/rails5.0.gemfile
gemfiles/rails5.1.gemfile
lib/arturo/version.rb

- Drops Ruby 2.6
- Drops Rails 5.0 & 5.1
- Test with Ruby 3.2

Release v2.8.0

---

lib/arturo/feature_caching.rb

To force a cache load during startup, some services at Zendesk have resorted to making a fake query in an initializer (`Arturo::Feature.find_feature "smth")`. This method will make this intent more explicit and readable.

bring back warm_cache! method

---

lib/arturo/feature_caching.rb

Instead of creating a temporary array with all Arturos only to convert it into a hash immediately, we should be building this hash directly. This will save (a little bit of) memory (as we will not be creating an unnecessary array). 
It also seems to be slightly faster: 
```ruby
require "benchmark/ips"
require 'random/formatter'
class Feature
attr_reader :symbol, :data
def initialize
@symbol = Random.alphanumeric(10)
@data = { Random.alphanumeric(3) => Random.alphanumeric(10) }
end
end
class Test
attr_reader :features
def initialize
@features = Array.new(1000) { |_index| Feature.new }
end
def old
Hash[features.map { |f| [f.symbol.to_sym, f] }]
end
def new
features.each_with_object({}) { |f, hash| hash[f.symbol.to_sym] = f }
end
end
test = Test.new
Benchmark.ips do |x|
x.report("previous, …
```

build cache hash using each_with_object

---

lib/arturo.rb
lib/arturo/feature_methods.rb
lib/arturo/version.rb

This commit renames `arturo/feature` to `arturo/feature_methods`. The reason for this is that we expect to have an `Arturo::Feature` class which collides with the filename of `arturo/feature` in the library. This causes problems with `zeitwerk` and `require`.
The module we define in `arturo/feature` is actually called `FeatureMethods` so this name change makes it more consistent with the contents.
This also changes `require` to `require_relative` and moves the require out of the module and to the top of the file.

Rename feature to feature_methods, reformat

---

lib/arturo.rb
spec/models/feature_spec.rb

For recipients that do not exist, we return `false` (this is also documented in the README). We can skip building the `Feature` object and potentially fetching data and return false immediately.

return false immediately for nil recipients

---

CHANGELOG.md
lib/arturo.rb
spec/dummy_app/config/application.rb

Applications that don’t use `FeaturesController` to manage Arturo features don’t need to automatically load the whole engine. Engine loading should be an explicit decision on an app’s part.

stop loading arturo/engine automatically

---

CHANGELOG.md
CONTRIBUTING.md
README.md

Particularly the rendered Changelog was unreadable without newlines.

Fix the markdown slightly

---

CHANGELOG.md
lib/arturo/version.rb

- Removes upper bounder on ActiveRecord.
- Drops support for Ruby < 3.0.
- Drops support for Rails < 6.0.

Release v4.1.0

---

app/controllers/arturo/features_controller.rb
lib/arturo/controller_filters.rb

`before_filter` got deprecated in Rails 5.1, and we only support Rails 6.0 and above, so there is no need to check whether we need it or `before_action`.

stop checking for before_filter

---

spec/models/whitelist_and_blacklist_spec.rb

The `'works with a post on holds'` spec in `controller_filters_spec.rb` was flaky. In it, we check that if a feature `:book_holds` has `deployment_percentage` set to 0, and we call require_feature `:book_holds` in a controller, then we receive 403 Forbidden from that controller.
However, if the `'works with global whitelisting'` spec ran as a final spec from its suite of six, and before the `:book_holds`, we still had a whitelist in place that would enable all features, so `enabled_for?` returned true for :book_holds:
```ruby
def enabled_for?(feature_recipient)
return false if feature_recipient.nil?
return false if blacklisted?(feature_recipient)
---> return true if  whitelisted?(feature_recipient) # returned true, so we never checked deployment_percentage …
```

clear whitelists and blacklists after running their specs

---

Rakefile

We have removed bump as a dependency in https://github.com/zendesk/arturo/commit/e644d0527e0110eeec22b14af046d0ab0d73ec6c, but still required it in the `Rakefile` which caused all rake tasks to fail.

stop requiring bump

---

.github/workflows/ci.yml
.github/workflows/rails_main_specs.yml

Instead of Zendesk forks which are not maintained anymore, as we have switched to a different security model for shared Github workflows.

use original checkout and setup-ruby actions

---

CHANGELOG.md
lib/arturo/feature_methods.rb
lib/arturo/version.rb

In the model-to-mixin rework for Arturo 3.0, we changed the load order, and this extension might not always get loaded before the `FeatureMethods` module. This doesn’t happen in Arturo’s own tests, but affects gems that depend on Arturo.

require indifferent_access extension explicitly

---

.github/workflows/rails_main_specs.yml
gemfiles/common.rb
gemfiles/rails6.0.gemfile
gemfiles/rails7.1.gemfile
gemfiles/rails_main.gemfile

ActiveRecord now requires sqlite3 >= 2.0[^1]. Also, we test with Rails main every day and it seems wasteful to test it with Ruby 3.1 & 3.2 when 3.3 should be sufficient.
[^1]:(https://github.com/rails/rails/blob/171c4e4d377d9653a79d38c94bdfadf1a2c4c312/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L14)

Fix Rails Main testing, only test with latest Ruby
